name: Build and deploy a container image to Azure Web Apps

on:
  push:
    branches:
    - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main

     
    - name: Log in to Docker Hub
    #- uses: azure/container-actions/docker-login@v1
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: axreki/demo-datacraft:${{ github.run_id }}

    #- name: Build and push the image tagged with the git commit hash
    #  run: |
    #    docker build . -t axreki/demo-datacraft:${{ github.run_id }}
    #    docker push axreki/demo-datacraft:${{ github.run_id }}

    # - name: Update image tag on the Azure Web App
    #   uses: azure/webapps-container-deploy@v1
    #   with:
    #     app-name: 'datacraft-docker-demo-app'
    #     #slot-name: '<your-slot-name>'
    #     images: 'axreki/demo-datacraft:${{ github.run_id }}'
    
    - uses: azure/webapps-deploy@v2
      with:
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
